-- Primero eliminamos las columnas antiguas
ALTER TABLE "SSC"."TBL_ACTIVIDADES"
    DROP COLUMN IF EXISTS "ACT_DESCRIPCION",
    DROP COLUMN IF EXISTS "ACT_META_FISICA",
    DROP COLUMN IF EXISTS "ACT_UNIDAD_MEDIDA",
    DROP COLUMN IF EXISTS "ACT_VALOR_UNITARIO",
    DROP COLUMN IF EXISTS "ACT_VALOR_TOTAL";

-- Luego agregamos las nuevas columnas
ALTER TABLE "SSC"."TBL_ACTIVIDADES"
    ADD COLUMN "ACT_ACTIVIDAD" VARCHAR NOT NULL,
    ADD COLUMN "ACT_METAFISICA" FLOAT NOT NULL,
    ADD COLUMN "ACT_PROYECTADO_FINANCIERO" BIGINT NOT NULL,
    ADD COLUMN "ACT_UNIDADES_AVANCE" VARCHAR NOT NULL;

-- Opcionalmente, si necesitas agregar índices
CREATE INDEX IF NOT EXISTS "idx_actividades_cuo_id" ON "SSC"."TBL_ACTIVIDADES"("ACT_CUO_ID"); 