-- Crear esquema si no existe
CREATE SCHEMA IF NOT EXISTS "SSC";

-- Crear tipos ENUM
CREATE TYPE "SSC"."USUARIO_ROL" AS ENUM ('ADMIN', 'SUPERVISOR');
CREATE TYPE "SSC"."CONTRATO_ESTADO" AS ENUM ('activo', 'terminado', 'suspendido', 'liquidado');
CREATE TYPE "SSC"."MODIFICACION_TIPO" AS ENUM ('SUSPENSION', 'PRORROGA');

-- Tabla Usuarios
CREATE TABLE IF NOT EXISTS "SSC"."TBL_USUARIOS" (
    "USU_CEDULA" VARCHAR(20) PRIMARY KEY,
    "USU_NOMBRE" VARCHAR(100) NOT NULL,
    "USU_EMAIL" VARCHAR(100) UNIQUE NOT NULL,
    "USU_PASSWORD" VARCHAR(100) NOT NULL,
    "USU_ROL" "SSC"."USUARIO_ROL" NOT NULL DEFAULT 'SUPERVISOR',
    "USU_CREATED_AT" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Tabla Contratos
CREATE TABLE IF NOT EXISTS "SSC"."TBL_CONTRATOS" (
    "CON_ID" SERIAL PRIMARY KEY,
    "CON_USU_CEDULA" VARCHAR(20) NOT NULL REFERENCES "SSC"."TBL_USUARIOS"("USU_CEDULA"),
    "CON_NRO_CONTRATO" VARCHAR(20) UNIQUE NOT NULL,
    "CON_ANO_SUSCRIPCION" SMALLINT NOT NULL,
    "CON_PROGRAMA" VARCHAR(255) NOT NULL,
    "CON_TIPO_CONTRATO" VARCHAR(100) NOT NULL,
    "CON_OBJETO" TEXT NOT NULL,
    "CON_IDENTIFICADOR_SIMPLE" VARCHAR(100) NOT NULL,
    "CON_SUPLENTES" VARCHAR(255),
    "CON_APOYO" VARCHAR(255),
    "CON_ESTADO" "SSC"."CONTRATO_ESTADO" DEFAULT 'activo',
    "CON_CONTRATISTA" VARCHAR(255) NOT NULL,
    "CON_NRO_PROCESO" VARCHAR(100) NOT NULL,
    "CON_FECHA_INI" DATE NOT NULL,
    "CON_FECHA_TER_INI" DATE NOT NULL,
    "CON_FECHA_TER_ACT" DATE NOT NULL,
    "CON_VALOR_INI" BIGINT NOT NULL,
    "CON_VALOR_TOTAL" BIGINT NOT NULL
);

-- Tabla CUO (Código Único de Obra)
CREATE TABLE IF NOT EXISTS "SSC"."TBL_CUO" (
    "CUO_ID" SERIAL PRIMARY KEY,
    "CUO_CON_ID" INTEGER NOT NULL REFERENCES "SSC"."TBL_CONTRATOS"("CON_ID"),
    "CUO_NRO" VARCHAR(20) NOT NULL,
    "CUO_LATITUD" DECIMAL(10,8) NOT NULL,
    "CUO_LONGITUD" DECIMAL(11,8) NOT NULL,
    "CUO_COMUNA" VARCHAR(50) NOT NULL,
    "CUO_BARRIO" VARCHAR(100) NOT NULL,
    "CUO_DESCRIPCION" TEXT NOT NULL
);

-- Tabla Actividades
CREATE TABLE IF NOT EXISTS "SSC"."TBL_ACTIVIDADES" (
    "ACT_ID" SERIAL PRIMARY KEY,
    "ACT_CUO_ID" INTEGER NOT NULL REFERENCES "SSC"."TBL_CUO"("CUO_ID"),
    "ACT_ACTIVIDAD" VARCHAR NOT NULL,
    "ACT_METAFISICA" FLOAT NOT NULL,
    "ACT_PROYECTADO_FINANCIERO" BIGINT NOT NULL,
    "ACT_UNIDADES_AVANCE" VARCHAR NOT NULL
);

-- Tabla Seguimiento General
CREATE TABLE IF NOT EXISTS "SSC"."TBL_SEGUIMIENTOGENERAL" (
    "SEG_ID" SERIAL PRIMARY KEY,
    "SEG_CON_ID" INTEGER NOT NULL REFERENCES "SSC"."TBL_CONTRATOS"("CON_ID"),
    "SEG_AVANCE_FINANCIERO" DECIMAL(15,2) NOT NULL,
    "SEG_AVANCE_FISICO" DECIMAL(5,2) NOT NULL,
    "SEG_CREATED_AT" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "SEG_OBSERVACIONES" TEXT
);

-- Tabla Seguimiento Actividad
CREATE TABLE IF NOT EXISTS "SSC"."TBL_SEGUIMIENTOACTIVIDAD" (
    "SEG_ID" SERIAL PRIMARY KEY,
    "SEG_ACT_ID" INTEGER NOT NULL REFERENCES "SSC"."TBL_ACTIVIDADES"("ACT_ID"),
    "SEG_AVANCE_FISICO" DECIMAL(5,2) NOT NULL,
    "SEG_COSTO_APROXIMADO" DECIMAL(15,2) NOT NULL,
    "SEG_CREATED_AT" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "SEG_DESCRIPCION_SEGUIMIENTO" TEXT NOT NULL,
    "SEG_PROYECCION_ACTIVIDADES" TEXT NOT NULL
);

-- Tabla Modificaciones
CREATE TABLE IF NOT EXISTS "SSC"."TBL_MODIFICACIONES" (
    "MOD_ID" SERIAL PRIMARY KEY,
    "MOD_CON_ID" INTEGER NOT NULL REFERENCES "SSC"."TBL_CONTRATOS"("CON_ID"),
    "MOD_TIPO" "SSC"."MODIFICACION_TIPO" NOT NULL,
    "MOD_FECHA_INICIAL" DATE NOT NULL,
    "MOD_FECHA_FINAL" DATE NOT NULL,
    "MOD_DURACION" INTEGER NOT NULL,
    "MOD_CREATED_AT" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "MOD_OBSERVACIONES" TEXT
);

-- Tabla Adiciones
CREATE TABLE IF NOT EXISTS "SSC"."TBL_ADICIONES" (
    "ADI_ID" SERIAL PRIMARY KEY,
    "ADI_CON_ID" INTEGER NOT NULL REFERENCES "SSC"."TBL_CONTRATOS"("CON_ID"),
    "ADI_VALOR_ADICION" BIGINT NOT NULL,
    "ADI_FECHA" DATE NOT NULL,
    "ADI_CREATED_AT" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "ADI_OBSERVACIONES" TEXT
);

-- Crear índices para mejorar el rendimiento
CREATE INDEX IF NOT EXISTS "idx_contratos_supervisor" ON "SSC"."TBL_CONTRATOS"("CON_USU_CEDULA");
CREATE INDEX IF NOT EXISTS "idx_cuo_contrato" ON "SSC"."TBL_CUO"("CUO_CON_ID");
CREATE INDEX IF NOT EXISTS "idx_actividades_cuo" ON "SSC"."TBL_ACTIVIDADES"("ACT_CUO_ID");
CREATE INDEX IF NOT EXISTS "idx_seguimiento_contrato" ON "SSC"."TBL_SEGUIMIENTOGENERAL"("SEG_CON_ID");
CREATE INDEX IF NOT EXISTS "idx_seguimiento_actividad" ON "SSC"."TBL_SEGUIMIENTOACTIVIDAD"("SEG_ACT_ID");
CREATE INDEX IF NOT EXISTS "idx_modificaciones_contrato" ON "SSC"."TBL_MODIFICACIONES"("MOD_CON_ID");
CREATE INDEX IF NOT EXISTS "idx_adiciones_contrato" ON "SSC"."TBL_ADICIONES"("ADI_CON_ID");
CREATE INDEX IF NOT EXISTS "idx_usuarios_rol" ON "SSC"."TBL_USUARIOS"("USU_ROL");

-- Crear vista para auditoría de roles
CREATE OR REPLACE VIEW "SSC"."VW_USUARIOS_ROLES" AS
SELECT 
    "USU_CEDULA" as cedula,
    "USU_NOMBRE" as nombre,
    "USU_EMAIL" as email,
    "USU_ROL" as rol,
    "USU_CREATED_AT" as fecha_creacion
FROM "SSC"."TBL_USUARIOS"
ORDER BY "USU_ROL", "USU_NOMBRE";

-- Agregar comentarios a las tablas y columnas principales
COMMENT ON TABLE "SSC"."TBL_USUARIOS" IS 'Almacena la información de los usuarios del sistema';
COMMENT ON COLUMN "SSC"."TBL_USUARIOS"."USU_ROL" IS 'Roles disponibles: ADMIN (acceso total), SUPERVISOR (gestión de contratos asignados)'; 